[project]
name = "rsibot"
version = "0.1.0"
description = "Python bot that pings me if crypto RSI looks interesting. [Learning Python Exercise]"
requires-python = ">=3.12"
dependencies = [
    "black>=25.11.0",
    "ccxt>=4.5.44",
    "pandas>=2.3.3",
    "pandas-ta>=0.4.71b0",
    "aiogram>=3.26.0",
]

[tool.black]
line-length = 80
